services:
  mongodb:
    image: mongo:6.0
    container_name: localmind-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: localmind
    volumes:
      - mongodb_data:/data/db
    networks:
      - localmind_network

volumes:
  mongodb_data:

networks:
  localmind_network:
